# Количество реплик
replicaCount: 6

# Уровень логирования
logLevel: debug

# Настройки UI
ui:
  # color: "#34577c"
  message: "Lesson 9: Routing"

# Отключить fault injection для стабильного тестирования
faults:
  delay: false
  error: false
  unhealthy: false
  unready: false
  testFail: false
  testTimeout: false

# Лимиты и запросы ресурсов
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

# Конфигурация Service
service:
  # Тип сервиса: NodePort для работы с gwin через node IP адреса
  type: NodePort
